comment: false

coverage:
  status:
    project:
      default:
        threshold: 0.05%
    patch:
      default:
        threshold: 0.05%

ignore:
  - "contracts"
  - "packages/profiler"
  # Disabled due to "cargo_tarpaulin: Failed to get test coverage! Error: Failed to run tests: Error running test - SIGILL raised in 5835"
  - "packages/vm"

flags:
  cosmwasm-crypto:
    paths:
      - packages/crypto/
  cosmwasm-derive:
    paths:
      - packages/derive/
  cosmwasm-schema:
    paths:
      - packages/schema/
  cosmwasm-schema-derive:
    paths:
      - packages/schema-derive/
  cosmwasm-std:
    paths:
      - packages/std/
  cosmwasm-storage:
    paths:
      - packages/storage/
